language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
script:
  - yarn build
  - | 
    zip -r release.zip .   
    -x "node_modules*"
    -x "*webpack.*.js"
    -x ".*"       
    -x "*.lock"
    -x "package.json" 
deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file: "release.zip"
  skip_cleanup: true
  on:
    tags: true
