language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
script:
  - yarn build
  - yarn run zip
deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file: "release.zip"
  skip_cleanup: true
  on:
    tags: true
